var tmp;
// 481 files
aa = [
"getting-started",
"_basic_concepts",
"_installation",
"_exploring_your_cluster",
"_cluster_health",
"_list_all_indices",
"_create_an_index",
"_index_and_query_a_document",
"_delete_an_index",
"_modifying_your_data",
"_updating_documents",
"_deleting_documents",
"_batch_processing",
"_exploring_your_data",
"_the_search_api",
"_introducing_the_query_language",
"_executing_searches",
"_executing_filters",
"_executing_aggregations",
"_conclusion",
"setup",
"setup-configuration",
"setup-service",
"setup-service-win",
"setup-dir-layout",
"setup-repositories",
"setup-upgrade",
"breaking-changes",
"breaking-changes-1.6",
"breaking-changes-1.5",
"breaking-changes-1.4",
"breaking-changes-1.0",
"_system_and_settings",
"_stats_and_info_apis",
"_indices_apis_2",
"_index_request",
"_search_requests",
"_multi_fields",
"_stopwords",
"_dates_without_years",
"_parameters",
"_return_values",
"_deprecations",
"_percolator_2",
"api-conventions",
"multi-index",
"common-options",
"url-access-control",
"docs",
"docs-index_",
"docs-get",
"docs-delete",
"docs-update",
"docs-multi-get",
"docs-bulk",
"docs-delete-by-query",
"docs-bulk-udp",
"docs-termvectors",
"docs-multi-termvectors",
"search",
"search-search",
"search-uri-request",
"search-request-body",
"search-request-query",
"search-request-from-size",
"search-request-sort",
"search-request-source-filtering",
"search-request-fields",
"search-request-script-fields",
"search-request-fielddata-fields",
"search-request-post-filter",
"search-request-highlighting",
"search-request-rescore",
"search-request-search-type",
"search-request-scroll",
"search-request-preference",
"search-request-explain",
"search-request-version",
"search-request-index-boost",
"search-request-min-score",
"search-request-named-queries-and-filters",
"search-request-inner-hits",
"search-template",
"search-shards",
"search-aggregations",
"search-aggregations-metrics-min-aggregation",
"search-aggregations-metrics-max-aggregation",
"search-aggregations-metrics-sum-aggregation",
"search-aggregations-metrics-avg-aggregation",
"search-aggregations-metrics-stats-aggregation",
"search-aggregations-metrics-extendedstats-aggregation",
"search-aggregations-metrics-valuecount-aggregation",
"search-aggregations-metrics-percentile-aggregation",
"search-aggregations-metrics-percentile-rank-aggregation",
"search-aggregations-metrics-cardinality-aggregation",
"search-aggregations-metrics-geobounds-aggregation",
"search-aggregations-metrics-top-hits-aggregation",
"search-aggregations-metrics-scripted-metric-aggregation",
"search-aggregations-bucket-global-aggregation",
"search-aggregations-bucket-filter-aggregation",
"search-aggregations-bucket-filters-aggregation",
"search-aggregations-bucket-missing-aggregation",
"search-aggregations-bucket-nested-aggregation",
"search-aggregations-bucket-reverse-nested-aggregation",
"search-aggregations-bucket-children-aggregation",
"search-aggregations-bucket-terms-aggregation",
"search-aggregations-bucket-significantterms-aggregation",
"search-aggregations-bucket-range-aggregation",
"search-aggregations-bucket-daterange-aggregation",
"search-aggregations-bucket-iprange-aggregation",
"search-aggregations-bucket-histogram-aggregation",
"search-aggregations-bucket-datehistogram-aggregation",
"search-aggregations-bucket-geodistance-aggregation",
"search-aggregations-bucket-geohashgrid-aggregation",
"search-facets",
"search-facets-terms-facet",
"search-facets-range-facet",
"search-facets-histogram-facet",
"search-facets-date-histogram-facet",
"search-facets-filter-facet",
"search-facets-query-facet",
"search-facets-statistical-facet",
"search-facets-terms-stats-facet",
"search-facets-geo-distance-facet",
"search-facets-migrating-to-aggs",
"search-suggesters",
"search-suggesters-term",
"search-suggesters-phrase",
"search-suggesters-completion",
"suggester-context",
"search-multi-search",
"search-count",
"search-exists",
"search-validate",
"search-explain",
"search-percolate",
"search-more-like-this",
"search-field-stats",
"indices",
"indices-create-index",
"indices-delete-index",
"indices-get-index",
"indices-exists",
"indices-open-close",
"indices-put-mapping",
"indices-get-mapping",
"indices-get-field-mapping",
"indices-types-exists",
"indices-delete-mapping",
"indices-aliases",
"indices-update-settings",
"indices-get-settings",
"indices-analyze",
"indices-templates",
"indices-warmers",
"indices-status",
"indices-stats",
"indices-segments",
"indices-recovery",
"indices-clearcache",
"indices-flush",
"indices-synced-flush",
"indices-refresh",
"indices-optimize",
"indices-shadow-replicas",
"_node_level_settings_related_to_shadow_replicas",
"indices-upgrade",
"cat",
"cat-alias",
"cat-allocation",
"cat-count",
"cat-fielddata",
"cat-health",
"cat-indices",
"cat-master",
"cat-nodes",
"cat-pending-tasks",
"cat-plugins",
"cat-recovery",
"cat-thread-pool",
"cat-shards",
"index-pattern",
"relocation",
"states",
"cat-segments",
"cluster",
"cluster-health",
"cluster-state",
"cluster-stats",
"cluster-pending",
"cluster-reroute",
"cluster-update-settings",
"cluster-nodes-stats",
"cluster-nodes-info",
"cluster-nodes-hot-threads",
"cluster-nodes-shutdown",
"query-dsl",
"query-dsl-queries",
"query-dsl-match-query",
"query-dsl-multi-match-query",
"query-dsl-bool-query",
"query-dsl-boosting-query",
"query-dsl-common-terms-query",
"query-dsl-constant-score-query",
"query-dsl-dis-max-query",
"query-dsl-filtered-query",
"query-dsl-flt-query",
"query-dsl-flt-field-query",
"query-dsl-function-score-query",
"query-dsl-fuzzy-query",
"query-dsl-geo-shape-query",
"query-dsl-has-child-query",
"query-dsl-has-parent-query",
"query-dsl-ids-query",
"query-dsl-indices-query",
"query-dsl-match-all-query",
"query-dsl-mlt-query",
"query-dsl-nested-query",
"query-dsl-prefix-query",
"query-dsl-query-string-query",
"query-dsl-simple-query-string-query",
"query-dsl-range-query",
"query-dsl-regexp-query",
"query-dsl-span-first-query",
"query-dsl-span-multi-term-query",
"query-dsl-span-near-query",
"query-dsl-span-not-query",
"query-dsl-span-or-query",
"query-dsl-span-term-query",
"query-dsl-term-query",
"query-dsl-terms-query",
"query-dsl-top-children-query",
"query-dsl-wildcard-query",
"query-dsl-minimum-should-match",
"query-dsl-multi-term-rewrite",
"query-dsl-template-query",
"query-dsl-filters",
"query-dsl-and-filter",
"query-dsl-bool-filter",
"query-dsl-exists-filter",
"query-dsl-geo-bounding-box-filter",
"query-dsl-geo-distance-filter",
"query-dsl-geo-distance-range-filter",
"query-dsl-geo-polygon-filter",
"query-dsl-geo-shape-filter",
"query-dsl-geohash-cell-filter",
"query-dsl-has-child-filter",
"query-dsl-has-parent-filter",
"query-dsl-ids-filter",
"query-dsl-indices-filter",
"query-dsl-limit-filter",
"query-dsl-match-all-filter",
"query-dsl-missing-filter",
"query-dsl-nested-filter",
"query-dsl-not-filter",
"query-dsl-or-filter",
"query-dsl-prefix-filter",
"query-dsl-query-filter",
"query-dsl-range-filter",
"query-dsl-regexp-filter",
"query-dsl-script-filter",
"query-dsl-term-filter",
"query-dsl-terms-filter",
"query-dsl-type-filter",
"mapping",
"mapping-fields",
"mapping-uid-field",
"mapping-id-field",
"mapping-type-field",
"mapping-source-field",
"mapping-all-field",
"mapping-analyzer-field",
"mapping-boost-field",
"mapping-parent-field",
"mapping-field-names-field",
"mapping-routing-field",
"mapping-index-field",
"mapping-size-field",
"mapping-timestamp-field",
"mapping-ttl-field",
"mapping-types",
"mapping-core-types",
"mapping-array-type",
"mapping-object-type",
"mapping-root-object-type",
"mapping-nested-type",
"mapping-ip-type",
"mapping-geo-point-type",
"mapping-geo-shape-type",
"mapping-attachment-type",
"mapping-date-format",
"mapping-dynamic-mapping",
"mapping-conf-mappings",
"mapping-meta",
"mapping-transform",
"_get_transformed",
"_immutable_transformation",
"analysis",
"analysis-analyzers",
"analysis-standard-analyzer",
"analysis-simple-analyzer",
"analysis-whitespace-analyzer",
"analysis-stop-analyzer",
"analysis-keyword-analyzer",
"analysis-pattern-analyzer",
"analysis-lang-analyzer",
"analysis-snowball-analyzer",
"analysis-custom-analyzer",
"analysis-tokenizers",
"analysis-standard-tokenizer",
"analysis-edgengram-tokenizer",
"analysis-keyword-tokenizer",
"analysis-letter-tokenizer",
"analysis-lowercase-tokenizer",
"analysis-ngram-tokenizer",
"analysis-whitespace-tokenizer",
"analysis-pattern-tokenizer",
"analysis-uaxurlemail-tokenizer",
"analysis-pathhierarchy-tokenizer",
"analysis-classic-tokenizer",
"analysis-thai-tokenizer",
"analysis-tokenfilters",
"analysis-standard-tokenfilter",
"analysis-asciifolding-tokenfilter",
"analysis-length-tokenfilter",
"analysis-lowercase-tokenfilter",
"analysis-uppercase-tokenfilter",
"analysis-ngram-tokenfilter",
"analysis-edgengram-tokenfilter",
"analysis-porterstem-tokenfilter",
"analysis-shingle-tokenfilter",
"analysis-stop-tokenfilter",
"analysis-word-delimiter-tokenfilter",
"analysis-stemmer-tokenfilter",
"analysis-stemmer-override-tokenfilter",
"analysis-keyword-marker-tokenfilter",
"analysis-keyword-repeat-tokenfilter",
"analysis-kstem-tokenfilter",
"analysis-snowball-tokenfilter",
"analysis-phonetic-tokenfilter",
"analysis-synonym-tokenfilter",
"analysis-compound-word-tokenfilter",
"analysis-reverse-tokenfilter",
"analysis-elision-tokenfilter",
"analysis-truncate-tokenfilter",
"analysis-unique-tokenfilter",
"analysis-pattern-capture-tokenfilter",
"analysis-pattern_replace-tokenfilter",
"analysis-trim-tokenfilter",
"analysis-limit-token-count-tokenfilter",
"analysis-hunspell-tokenfilter",
"analysis-common-grams-tokenfilter",
"analysis-normalization-tokenfilter",
"analysis-cjk-width-tokenfilter",
"analysis-cjk-bigram-tokenfilter",
"analysis-delimited-payload-tokenfilter",
"analysis-keep-words-tokenfilter",
"analysis-keep-types-tokenfilter",
"analysis-classic-tokenfilter",
"analysis-apostrophe-tokenfilter",
"analysis-charfilters",
"analysis-mapping-charfilter",
"analysis-htmlstrip-charfilter",
"analysis-pattern-replace-charfilter",
"analysis-icu-plugin",
"modules",
"modules-cluster",
"modules-discovery",
"modules-discovery-azure",
"modules-discovery-ec2",
"modules-discovery-gce",
"modules-discovery-zen",
"modules-gateway",
"modules-gateway-local",
"modules-http",
"modules-indices",
"modules-memcached",
"modules-network",
"modules-node",
"modules-tribe",
"modules-plugins",
"modules-scripting",
"modules-advanced-scripting",
"modules-threadpool",
"modules-thrift",
"modules-transport",
"modules-snapshots",
"index-modules",
"index-modules-analysis",
"index-modules-allocation",
"delayed-allocation",
"recovery-prioritization",
"_total_shards_per_node",
"disk",
"index-modules-slowlog",
"index-modules-merge",
"index-modules-store",
"index-modules-mapper",
"index-modules-translog",
"index-modules-cache",
"index-modules-shard-query-cache",
"index-modules-fielddata",
"fielddata-formats",
"index-modules-similarity",
"testing",
"testing-framework",
"why-randomized-testing",
"using-elasticsearch-test-classes",
"unit-tests",
"integration-tests",
"parametrized-tests",
"randomized-testing",
"assertions",
"glossary",
"kibana-guide",
"using-kibana-for-the-first-time",
"import-some-data",
"accessing-the-kibana-interface",
"the-first-search",
"configuring-another-index",
"_next_steps",
"working-with-queries-and-filters",
"our-dashboard",
"queries",
"multiple-queries",
"colors-and-legends",
"filters",
"_more_reading",
"rows-and-panels",
"loading-a-blank-dashboard",
"adding-a-row",
"the-row-controls",
"adding-panels",
"collapsing-and-expanding-rows",
"editing-rows",
"moving-and-removing-panels",
"moving-and-removing-rows",
"_next_steps_2",
"saving-and-loading-dashboards",
"saving-your-awesome-dashboard",
"recalling-your-dashboard",
"sharing-dashboards",
"saving-a-static-dashboard",
"_next_steps_3",
"_dashboard_schema",
"services",
"pulldown",
"nav",
"loader",
"rows-array",
"index-settings",
"the-rest",
"importing-schemas",
"templated-and-scripted-dashboards",
"the-dashboard-directory",
"templated-dashboards-.json",
"scripted-dashboards-.js",
"_parameters",
"panels",
"_bettermap",
"_parameters_2",
"_column",
"_parameters_3",
"_goal",
"_parameters_4",
"_histogram",
"_parameters_5",
"_hits",
"_parameters_6",
"_map",
"_parameters_7",
"_sparklines",
"_parameters_8",
"_table",
"_parameters_9",
"_terms",
"_parameters_10",
"_text",
"_parameters_11",
"_trends",
"_parameters_12",
]

aa.forEach(function (query) {
    try {
        if (!document.getElementById(query)) {
            console.error(query);
        }
    } catch (error) {
        console.error(query);
        console.error(error);
    }
});
bb = {};
aa.forEach(function (key) {
    bb[key] = true;
});
console.assert(aa.length = 481);
console.assert(Object.keys(bb).length = 481);

idDict = {};
idDuplicateDict = {};
Array.from(document.querySelectorAll('[id]')).forEach(function (element) {
    idDict[element.id] = true;
    if (!idDuplicateDict[element.id] &&
            document.querySelectorAll('[id="' + element.id+ '"]').length > 1 &&
            document.querySelector('[href="#' + element.id+ '"]')) {
        idDuplicateDict[element.id] = true;
        console.error(element.id);
        console.error(document.querySelectorAll('[href="#' + element.id+ '"]'));
    }
});
hrefDict = {};
Array.from(document.querySelectorAll('[href]')).forEach(function (element) {
    href = element.href;
    if (href.indexOf('file://') !== 0) {
        return;
    }
    href = href.split('/').slice(-1)[0].split('#').slice(-1)[0].replace('.html', '');
    if (!href || href === 'index') {
        console.error(element.href);
        console.error(element);
    }
    hrefDict[href] = true;
});
console.error(Object.keys(hrefDict).length);
Object.keys(hrefDict).forEach(function (key) {
    if (!idDict[key]) {
        console.error(JSON.stringify(key));
    }
});

//!! Array.from(document.querySelectorAll('[href]')).forEach(function (element) {
    //!! href = element.href;
    //!! if (href.indexOf('file://') !== 0) {
        //!! return;
    //!! }
    //!! href = href.split('/').slice(-1)[0].split('#').slice(-1)[0].replace('.html', '');
    //!! if (!href || href === 'index') {
        //!! console.error(element.href);
        //!! console.error(element);
        //!! return;
    //!! }
    //!! element.href = '#' + href;
//!! });

/*
undegenerate _parameters

VM17740:513 (6) [a, a, a, a, a, a]
(anonymous) @ VM17740:513
(anonymous) @ VM17740:506
VM17740:512 _parameters_2
(anonymous) @ VM17740:512
(anonymous) @ VM17740:506
VM17740:513 (3) [a, a, a]
(anonymous) @ VM17740:513
(anonymous) @ VM17740:506
VM17740:512 _parameters_3
(anonymous) @ VM17740:512
(anonymous) @ VM17740:506
VM17740:513 (3) [a, a, a]
(anonymous) @ VM17740:513
(anonymous) @ VM17740:506
VM17740:512 _parameters_4
(anonymous) @ VM17740:512
(anonymous) @ VM17740:506
VM17740:513 (3) [a, a, a]
(anonymous) @ VM17740:513
(anonymous) @ VM17740:506
VM17740:512 _parameters_5
(anonymous) @ VM17740:512
(anonymous) @ VM17740:506
VM17740:513 (3) [a, a, a]
(anonymous) @ VM17740:513
(anonymous) @ VM17740:506
VM17740:512 _parameters_6
(anonymous) @ VM17740:512
(anonymous) @ VM17740:506
VM17740:513 (3) [a, a, a]
(anonymous) @ VM17740:513
(anonymous) @ VM17740:506
VM17740:512 _parameters_7
(anonymous) @ VM17740:512
(anonymous) @ VM17740:506
VM17740:513 (3) [a, a, a]
(anonymous) @ VM17740:513
(anonymous) @ VM17740:506
VM17740:512 _parameters_8
(anonymous) @ VM17740:512
(anonymous) @ VM17740:506
VM17740:513 (3) [a, a, a]
*/
