# 484 files
echo > all.html
cat elasticsearch.1.7/index.html >> all.html; echo >> all.html
cat kibana.3.0/index.html >> all.html; echo >> all.html
cat elasticsearch.1.7/getting-started.html >> all.html; echo >> all.html
cat elasticsearch.1.7/getting-started.html >> all.html; echo >> all.html
cat elasticsearch.1.7/_basic_concepts.html >> all.html; echo >> all.html
cat elasticsearch.1.7/_installation.html >> all.html; echo >> all.html
cat elasticsearch.1.7/_exploring_your_cluster.html >> all.html; echo >> all.html
cat elasticsearch.1.7/_cluster_health.html >> all.html; echo >> all.html
cat elasticsearch.1.7/_list_all_indices.html >> all.html; echo >> all.html
cat elasticsearch.1.7/_create_an_index.html >> all.html; echo >> all.html
cat elasticsearch.1.7/_index_and_query_a_document.html >> all.html; echo >> all.html
cat elasticsearch.1.7/_delete_an_index.html >> all.html; echo >> all.html
cat elasticsearch.1.7/_modifying_your_data.html >> all.html; echo >> all.html
cat elasticsearch.1.7/_updating_documents.html >> all.html; echo >> all.html
cat elasticsearch.1.7/_deleting_documents.html >> all.html; echo >> all.html
cat elasticsearch.1.7/_batch_processing.html >> all.html; echo >> all.html
cat elasticsearch.1.7/_exploring_your_data.html >> all.html; echo >> all.html
cat elasticsearch.1.7/_the_search_api.html >> all.html; echo >> all.html
cat elasticsearch.1.7/_introducing_the_query_language.html >> all.html; echo >> all.html
cat elasticsearch.1.7/_executing_searches.html >> all.html; echo >> all.html
cat elasticsearch.1.7/_executing_filters.html >> all.html; echo >> all.html
cat elasticsearch.1.7/_executing_aggregations.html >> all.html; echo >> all.html
cat elasticsearch.1.7/_conclusion.html >> all.html; echo >> all.html
cat elasticsearch.1.7/setup.html >> all.html; echo >> all.html
cat elasticsearch.1.7/setup-configuration.html >> all.html; echo >> all.html
cat elasticsearch.1.7/setup-service.html >> all.html; echo >> all.html
cat elasticsearch.1.7/setup-service-win.html >> all.html; echo >> all.html
cat elasticsearch.1.7/setup-dir-layout.html >> all.html; echo >> all.html
cat elasticsearch.1.7/setup-repositories.html >> all.html; echo >> all.html
cat elasticsearch.1.7/setup-upgrade.html >> all.html; echo >> all.html
cat elasticsearch.1.7/breaking-changes.html >> all.html; echo >> all.html
cat elasticsearch.1.7/breaking-changes-1.6.html >> all.html; echo >> all.html
cat elasticsearch.1.7/breaking-changes-1.5.html >> all.html; echo >> all.html
cat elasticsearch.1.7/breaking-changes-1.4.html >> all.html; echo >> all.html
cat elasticsearch.1.7/breaking-changes-1.0.html >> all.html; echo >> all.html
cat elasticsearch.1.7/_system_and_settings.html >> all.html; echo >> all.html
cat elasticsearch.1.7/_stats_and_info_apis.html >> all.html; echo >> all.html
cat elasticsearch.1.7/_indices_apis_2.html >> all.html; echo >> all.html
cat elasticsearch.1.7/_index_request.html >> all.html; echo >> all.html
cat elasticsearch.1.7/_search_requests.html >> all.html; echo >> all.html
cat elasticsearch.1.7/_multi_fields.html >> all.html; echo >> all.html
cat elasticsearch.1.7/_stopwords.html >> all.html; echo >> all.html
cat elasticsearch.1.7/_dates_without_years.html >> all.html; echo >> all.html
cat elasticsearch.1.7/_parameters.html >> all.html; echo >> all.html
cat elasticsearch.1.7/_return_values.html >> all.html; echo >> all.html
cat elasticsearch.1.7/_deprecations.html >> all.html; echo >> all.html
cat elasticsearch.1.7/_percolator_2.html >> all.html; echo >> all.html
cat elasticsearch.1.7/api-conventions.html >> all.html; echo >> all.html
cat elasticsearch.1.7/multi-index.html >> all.html; echo >> all.html
cat elasticsearch.1.7/common-options.html >> all.html; echo >> all.html
cat elasticsearch.1.7/url-access-control.html >> all.html; echo >> all.html
cat elasticsearch.1.7/docs.html >> all.html; echo >> all.html
cat elasticsearch.1.7/docs-index_.html >> all.html; echo >> all.html
cat elasticsearch.1.7/docs-get.html >> all.html; echo >> all.html
cat elasticsearch.1.7/docs-delete.html >> all.html; echo >> all.html
cat elasticsearch.1.7/docs-update.html >> all.html; echo >> all.html
cat elasticsearch.1.7/docs-multi-get.html >> all.html; echo >> all.html
cat elasticsearch.1.7/docs-bulk.html >> all.html; echo >> all.html
cat elasticsearch.1.7/docs-delete-by-query.html >> all.html; echo >> all.html
cat elasticsearch.1.7/docs-bulk-udp.html >> all.html; echo >> all.html
cat elasticsearch.1.7/docs-termvectors.html >> all.html; echo >> all.html
cat elasticsearch.1.7/docs-multi-termvectors.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-search.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-uri-request.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-request-body.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-request-query.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-request-from-size.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-request-sort.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-request-source-filtering.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-request-fields.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-request-script-fields.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-request-fielddata-fields.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-request-post-filter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-request-highlighting.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-request-rescore.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-request-search-type.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-request-scroll.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-request-preference.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-request-explain.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-request-version.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-request-index-boost.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-request-min-score.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-request-named-queries-and-filters.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-request-inner-hits.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-template.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-shards.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-aggregations.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-aggregations-metrics-min-aggregation.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-aggregations-metrics-max-aggregation.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-aggregations-metrics-sum-aggregation.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-aggregations-metrics-avg-aggregation.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-aggregations-metrics-stats-aggregation.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-aggregations-metrics-extendedstats-aggregation.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-aggregations-metrics-valuecount-aggregation.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-aggregations-metrics-percentile-aggregation.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-aggregations-metrics-percentile-rank-aggregation.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-aggregations-metrics-cardinality-aggregation.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-aggregations-metrics-geobounds-aggregation.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-aggregations-metrics-top-hits-aggregation.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-aggregations-metrics-scripted-metric-aggregation.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-aggregations-bucket-global-aggregation.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-aggregations-bucket-filter-aggregation.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-aggregations-bucket-filters-aggregation.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-aggregations-bucket-missing-aggregation.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-aggregations-bucket-nested-aggregation.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-aggregations-bucket-reverse-nested-aggregation.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-aggregations-bucket-children-aggregation.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-aggregations-bucket-terms-aggregation.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-aggregations-bucket-significantterms-aggregation.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-aggregations-bucket-range-aggregation.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-aggregations-bucket-daterange-aggregation.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-aggregations-bucket-iprange-aggregation.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-aggregations-bucket-histogram-aggregation.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-aggregations-bucket-datehistogram-aggregation.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-aggregations-bucket-geodistance-aggregation.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-aggregations-bucket-geohashgrid-aggregation.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-facets.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-facets-terms-facet.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-facets-range-facet.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-facets-histogram-facet.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-facets-date-histogram-facet.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-facets-filter-facet.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-facets-query-facet.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-facets-statistical-facet.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-facets-terms-stats-facet.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-facets-geo-distance-facet.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-facets-migrating-to-aggs.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-suggesters.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-suggesters-term.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-suggesters-phrase.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-suggesters-completion.html >> all.html; echo >> all.html
cat elasticsearch.1.7/suggester-context.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-multi-search.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-count.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-exists.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-validate.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-explain.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-percolate.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-more-like-this.html >> all.html; echo >> all.html
cat elasticsearch.1.7/search-field-stats.html >> all.html; echo >> all.html
cat elasticsearch.1.7/indices.html >> all.html; echo >> all.html
cat elasticsearch.1.7/indices-create-index.html >> all.html; echo >> all.html
cat elasticsearch.1.7/indices-delete-index.html >> all.html; echo >> all.html
cat elasticsearch.1.7/indices-get-index.html >> all.html; echo >> all.html
cat elasticsearch.1.7/indices-exists.html >> all.html; echo >> all.html
cat elasticsearch.1.7/indices-open-close.html >> all.html; echo >> all.html
cat elasticsearch.1.7/indices-put-mapping.html >> all.html; echo >> all.html
cat elasticsearch.1.7/indices-get-mapping.html >> all.html; echo >> all.html
cat elasticsearch.1.7/indices-get-field-mapping.html >> all.html; echo >> all.html
cat elasticsearch.1.7/indices-types-exists.html >> all.html; echo >> all.html
cat elasticsearch.1.7/indices-delete-mapping.html >> all.html; echo >> all.html
cat elasticsearch.1.7/indices-aliases.html >> all.html; echo >> all.html
cat elasticsearch.1.7/indices-update-settings.html >> all.html; echo >> all.html
cat elasticsearch.1.7/indices-get-settings.html >> all.html; echo >> all.html
cat elasticsearch.1.7/indices-analyze.html >> all.html; echo >> all.html
cat elasticsearch.1.7/indices-templates.html >> all.html; echo >> all.html
cat elasticsearch.1.7/indices-warmers.html >> all.html; echo >> all.html
cat elasticsearch.1.7/indices-status.html >> all.html; echo >> all.html
cat elasticsearch.1.7/indices-stats.html >> all.html; echo >> all.html
cat elasticsearch.1.7/indices-segments.html >> all.html; echo >> all.html
cat elasticsearch.1.7/indices-recovery.html >> all.html; echo >> all.html
cat elasticsearch.1.7/indices-clearcache.html >> all.html; echo >> all.html
cat elasticsearch.1.7/indices-flush.html >> all.html; echo >> all.html
cat elasticsearch.1.7/indices-synced-flush.html >> all.html; echo >> all.html
cat elasticsearch.1.7/indices-refresh.html >> all.html; echo >> all.html
cat elasticsearch.1.7/indices-optimize.html >> all.html; echo >> all.html
cat elasticsearch.1.7/indices-shadow-replicas.html >> all.html; echo >> all.html
cat elasticsearch.1.7/_node_level_settings_related_to_shadow_replicas.html >> all.html; echo >> all.html
cat elasticsearch.1.7/indices-upgrade.html >> all.html; echo >> all.html
cat elasticsearch.1.7/cat.html >> all.html; echo >> all.html
cat elasticsearch.1.7/cat-alias.html >> all.html; echo >> all.html
cat elasticsearch.1.7/cat-allocation.html >> all.html; echo >> all.html
cat elasticsearch.1.7/cat-count.html >> all.html; echo >> all.html
cat elasticsearch.1.7/cat-fielddata.html >> all.html; echo >> all.html
cat elasticsearch.1.7/cat-health.html >> all.html; echo >> all.html
cat elasticsearch.1.7/cat-indices.html >> all.html; echo >> all.html
cat elasticsearch.1.7/cat-master.html >> all.html; echo >> all.html
cat elasticsearch.1.7/cat-nodes.html >> all.html; echo >> all.html
cat elasticsearch.1.7/cat-pending-tasks.html >> all.html; echo >> all.html
cat elasticsearch.1.7/cat-plugins.html >> all.html; echo >> all.html
cat elasticsearch.1.7/cat-recovery.html >> all.html; echo >> all.html
cat elasticsearch.1.7/cat-thread-pool.html >> all.html; echo >> all.html
cat elasticsearch.1.7/cat-shards.html >> all.html; echo >> all.html
cat elasticsearch.1.7/index-pattern.html >> all.html; echo >> all.html
cat elasticsearch.1.7/relocation.html >> all.html; echo >> all.html
cat elasticsearch.1.7/states.html >> all.html; echo >> all.html
cat elasticsearch.1.7/cat-segments.html >> all.html; echo >> all.html
cat elasticsearch.1.7/cluster.html >> all.html; echo >> all.html
cat elasticsearch.1.7/cluster-health.html >> all.html; echo >> all.html
cat elasticsearch.1.7/cluster-state.html >> all.html; echo >> all.html
cat elasticsearch.1.7/cluster-stats.html >> all.html; echo >> all.html
cat elasticsearch.1.7/cluster-pending.html >> all.html; echo >> all.html
cat elasticsearch.1.7/cluster-reroute.html >> all.html; echo >> all.html
cat elasticsearch.1.7/cluster-update-settings.html >> all.html; echo >> all.html
cat elasticsearch.1.7/cluster-nodes-stats.html >> all.html; echo >> all.html
cat elasticsearch.1.7/cluster-nodes-info.html >> all.html; echo >> all.html
cat elasticsearch.1.7/cluster-nodes-hot-threads.html >> all.html; echo >> all.html
cat elasticsearch.1.7/cluster-nodes-shutdown.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-queries.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-match-query.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-multi-match-query.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-bool-query.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-boosting-query.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-common-terms-query.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-constant-score-query.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-dis-max-query.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-filtered-query.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-flt-query.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-flt-field-query.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-function-score-query.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-fuzzy-query.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-geo-shape-query.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-has-child-query.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-has-parent-query.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-ids-query.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-indices-query.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-match-all-query.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-mlt-query.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-nested-query.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-prefix-query.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-query-string-query.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-simple-query-string-query.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-range-query.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-regexp-query.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-span-first-query.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-span-multi-term-query.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-span-near-query.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-span-not-query.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-span-or-query.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-span-term-query.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-term-query.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-terms-query.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-top-children-query.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-wildcard-query.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-minimum-should-match.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-multi-term-rewrite.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-template-query.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-filters.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-and-filter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-bool-filter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-exists-filter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-geo-bounding-box-filter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-geo-distance-filter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-geo-distance-range-filter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-geo-polygon-filter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-geo-shape-filter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-geohash-cell-filter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-has-child-filter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-has-parent-filter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-ids-filter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-indices-filter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-limit-filter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-match-all-filter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-missing-filter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-nested-filter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-not-filter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-or-filter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-prefix-filter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-query-filter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-range-filter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-regexp-filter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-script-filter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-term-filter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-terms-filter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/query-dsl-type-filter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/mapping.html >> all.html; echo >> all.html
cat elasticsearch.1.7/mapping-fields.html >> all.html; echo >> all.html
cat elasticsearch.1.7/mapping-uid-field.html >> all.html; echo >> all.html
cat elasticsearch.1.7/mapping-id-field.html >> all.html; echo >> all.html
cat elasticsearch.1.7/mapping-type-field.html >> all.html; echo >> all.html
cat elasticsearch.1.7/mapping-source-field.html >> all.html; echo >> all.html
cat elasticsearch.1.7/mapping-all-field.html >> all.html; echo >> all.html
cat elasticsearch.1.7/mapping-analyzer-field.html >> all.html; echo >> all.html
cat elasticsearch.1.7/mapping-boost-field.html >> all.html; echo >> all.html
cat elasticsearch.1.7/mapping-parent-field.html >> all.html; echo >> all.html
cat elasticsearch.1.7/mapping-field-names-field.html >> all.html; echo >> all.html
cat elasticsearch.1.7/mapping-routing-field.html >> all.html; echo >> all.html
cat elasticsearch.1.7/mapping-index-field.html >> all.html; echo >> all.html
cat elasticsearch.1.7/mapping-size-field.html >> all.html; echo >> all.html
cat elasticsearch.1.7/mapping-timestamp-field.html >> all.html; echo >> all.html
cat elasticsearch.1.7/mapping-ttl-field.html >> all.html; echo >> all.html
cat elasticsearch.1.7/mapping-types.html >> all.html; echo >> all.html
cat elasticsearch.1.7/mapping-core-types.html >> all.html; echo >> all.html
cat elasticsearch.1.7/mapping-array-type.html >> all.html; echo >> all.html
cat elasticsearch.1.7/mapping-object-type.html >> all.html; echo >> all.html
cat elasticsearch.1.7/mapping-root-object-type.html >> all.html; echo >> all.html
cat elasticsearch.1.7/mapping-nested-type.html >> all.html; echo >> all.html
cat elasticsearch.1.7/mapping-ip-type.html >> all.html; echo >> all.html
cat elasticsearch.1.7/mapping-geo-point-type.html >> all.html; echo >> all.html
cat elasticsearch.1.7/mapping-geo-shape-type.html >> all.html; echo >> all.html
cat elasticsearch.1.7/mapping-attachment-type.html >> all.html; echo >> all.html
cat elasticsearch.1.7/mapping-date-format.html >> all.html; echo >> all.html
cat elasticsearch.1.7/mapping-dynamic-mapping.html >> all.html; echo >> all.html
cat elasticsearch.1.7/mapping-conf-mappings.html >> all.html; echo >> all.html
cat elasticsearch.1.7/mapping-meta.html >> all.html; echo >> all.html
cat elasticsearch.1.7/mapping-transform.html >> all.html; echo >> all.html
cat elasticsearch.1.7/_get_transformed.html >> all.html; echo >> all.html
cat elasticsearch.1.7/_immutable_transformation.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-analyzers.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-standard-analyzer.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-simple-analyzer.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-whitespace-analyzer.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-stop-analyzer.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-keyword-analyzer.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-pattern-analyzer.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-lang-analyzer.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-snowball-analyzer.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-custom-analyzer.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-tokenizers.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-standard-tokenizer.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-edgengram-tokenizer.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-keyword-tokenizer.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-letter-tokenizer.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-lowercase-tokenizer.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-ngram-tokenizer.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-whitespace-tokenizer.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-pattern-tokenizer.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-uaxurlemail-tokenizer.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-pathhierarchy-tokenizer.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-classic-tokenizer.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-thai-tokenizer.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-tokenfilters.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-standard-tokenfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-asciifolding-tokenfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-length-tokenfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-lowercase-tokenfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-uppercase-tokenfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-ngram-tokenfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-edgengram-tokenfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-porterstem-tokenfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-shingle-tokenfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-stop-tokenfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-word-delimiter-tokenfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-stemmer-tokenfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-stemmer-override-tokenfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-keyword-marker-tokenfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-keyword-repeat-tokenfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-kstem-tokenfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-snowball-tokenfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-phonetic-tokenfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-synonym-tokenfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-compound-word-tokenfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-reverse-tokenfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-elision-tokenfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-truncate-tokenfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-unique-tokenfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-pattern-capture-tokenfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-pattern_replace-tokenfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-trim-tokenfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-limit-token-count-tokenfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-hunspell-tokenfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-common-grams-tokenfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-normalization-tokenfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-cjk-width-tokenfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-cjk-bigram-tokenfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-delimited-payload-tokenfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-keep-words-tokenfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-keep-types-tokenfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-classic-tokenfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-apostrophe-tokenfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-charfilters.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-mapping-charfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-htmlstrip-charfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-pattern-replace-charfilter.html >> all.html; echo >> all.html
cat elasticsearch.1.7/analysis-icu-plugin.html >> all.html; echo >> all.html
cat elasticsearch.1.7/modules.html >> all.html; echo >> all.html
cat elasticsearch.1.7/modules-cluster.html >> all.html; echo >> all.html
cat elasticsearch.1.7/modules-discovery.html >> all.html; echo >> all.html
cat elasticsearch.1.7/modules-discovery-azure.html >> all.html; echo >> all.html
cat elasticsearch.1.7/modules-discovery-ec2.html >> all.html; echo >> all.html
cat elasticsearch.1.7/modules-discovery-gce.html >> all.html; echo >> all.html
cat elasticsearch.1.7/modules-discovery-zen.html >> all.html; echo >> all.html
cat elasticsearch.1.7/modules-gateway.html >> all.html; echo >> all.html
cat elasticsearch.1.7/modules-gateway-local.html >> all.html; echo >> all.html
cat elasticsearch.1.7/modules-http.html >> all.html; echo >> all.html
cat elasticsearch.1.7/modules-indices.html >> all.html; echo >> all.html
cat elasticsearch.1.7/modules-memcached.html >> all.html; echo >> all.html
cat elasticsearch.1.7/modules-network.html >> all.html; echo >> all.html
cat elasticsearch.1.7/modules-node.html >> all.html; echo >> all.html
cat elasticsearch.1.7/modules-tribe.html >> all.html; echo >> all.html
cat elasticsearch.1.7/modules-plugins.html >> all.html; echo >> all.html
cat elasticsearch.1.7/modules-scripting.html >> all.html; echo >> all.html
cat elasticsearch.1.7/modules-advanced-scripting.html >> all.html; echo >> all.html
cat elasticsearch.1.7/modules-threadpool.html >> all.html; echo >> all.html
cat elasticsearch.1.7/modules-thrift.html >> all.html; echo >> all.html
cat elasticsearch.1.7/modules-transport.html >> all.html; echo >> all.html
cat elasticsearch.1.7/modules-snapshots.html >> all.html; echo >> all.html
cat elasticsearch.1.7/index-modules.html >> all.html; echo >> all.html
cat elasticsearch.1.7/index-modules-analysis.html >> all.html; echo >> all.html
cat elasticsearch.1.7/index-modules-allocation.html >> all.html; echo >> all.html
cat elasticsearch.1.7/delayed-allocation.html >> all.html; echo >> all.html
cat elasticsearch.1.7/recovery-prioritization.html >> all.html; echo >> all.html
cat elasticsearch.1.7/_total_shards_per_node.html >> all.html; echo >> all.html
cat elasticsearch.1.7/disk.html >> all.html; echo >> all.html
cat elasticsearch.1.7/index-modules-slowlog.html >> all.html; echo >> all.html
cat elasticsearch.1.7/index-modules-merge.html >> all.html; echo >> all.html
cat elasticsearch.1.7/index-modules-store.html >> all.html; echo >> all.html
cat elasticsearch.1.7/index-modules-mapper.html >> all.html; echo >> all.html
cat elasticsearch.1.7/index-modules-translog.html >> all.html; echo >> all.html
cat elasticsearch.1.7/index-modules-cache.html >> all.html; echo >> all.html
cat elasticsearch.1.7/index-modules-shard-query-cache.html >> all.html; echo >> all.html
cat elasticsearch.1.7/index-modules-fielddata.html >> all.html; echo >> all.html
cat elasticsearch.1.7/fielddata-formats.html >> all.html; echo >> all.html
cat elasticsearch.1.7/index-modules-similarity.html >> all.html; echo >> all.html
cat elasticsearch.1.7/testing.html >> all.html; echo >> all.html
cat elasticsearch.1.7/testing-framework.html >> all.html; echo >> all.html
cat elasticsearch.1.7/why-randomized-testing.html >> all.html; echo >> all.html
cat elasticsearch.1.7/using-elasticsearch-test-classes.html >> all.html; echo >> all.html
cat elasticsearch.1.7/unit-tests.html >> all.html; echo >> all.html
cat elasticsearch.1.7/integration-tests.html >> all.html; echo >> all.html
cat elasticsearch.1.7/parametrized-tests.html >> all.html; echo >> all.html
cat elasticsearch.1.7/randomized-testing.html >> all.html; echo >> all.html
cat elasticsearch.1.7/assertions.html >> all.html; echo >> all.html
cat elasticsearch.1.7/glossary.html >> all.html; echo >> all.html
cat kibana.3.0/kibana-guide.html >> all.html; echo >> all.html
cat kibana.3.0/using-kibana-for-the-first-time.html >> all.html; echo >> all.html
cat kibana.3.0/import-some-data.html >> all.html; echo >> all.html
cat kibana.3.0/accessing-the-kibana-interface.html >> all.html; echo >> all.html
cat kibana.3.0/the-first-search.html >> all.html; echo >> all.html
cat kibana.3.0/configuring-another-index.html >> all.html; echo >> all.html
cat kibana.3.0/_next_steps.html >> all.html; echo >> all.html
cat kibana.3.0/working-with-queries-and-filters.html >> all.html; echo >> all.html
cat kibana.3.0/our-dashboard.html >> all.html; echo >> all.html
cat kibana.3.0/queries.html >> all.html; echo >> all.html
cat kibana.3.0/multiple-queries.html >> all.html; echo >> all.html
cat kibana.3.0/colors-and-legends.html >> all.html; echo >> all.html
cat kibana.3.0/filters.html >> all.html; echo >> all.html
cat kibana.3.0/_more_reading.html >> all.html; echo >> all.html
cat kibana.3.0/rows-and-panels.html >> all.html; echo >> all.html
cat kibana.3.0/loading-a-blank-dashboard.html >> all.html; echo >> all.html
cat kibana.3.0/adding-a-row.html >> all.html; echo >> all.html
cat kibana.3.0/the-row-controls.html >> all.html; echo >> all.html
cat kibana.3.0/adding-panels.html >> all.html; echo >> all.html
cat kibana.3.0/collapsing-and-expanding-rows.html >> all.html; echo >> all.html
cat kibana.3.0/editing-rows.html >> all.html; echo >> all.html
cat kibana.3.0/moving-and-removing-panels.html >> all.html; echo >> all.html
cat kibana.3.0/moving-and-removing-rows.html >> all.html; echo >> all.html
cat kibana.3.0/_next_steps_2.html >> all.html; echo >> all.html
cat kibana.3.0/saving-and-loading-dashboards.html >> all.html; echo >> all.html
cat kibana.3.0/saving-your-awesome-dashboard.html >> all.html; echo >> all.html
cat kibana.3.0/recalling-your-dashboard.html >> all.html; echo >> all.html
cat kibana.3.0/sharing-dashboards.html >> all.html; echo >> all.html
cat kibana.3.0/saving-a-static-dashboard.html >> all.html; echo >> all.html
cat kibana.3.0/_next_steps_3.html >> all.html; echo >> all.html
cat kibana.3.0/_dashboard_schema.html >> all.html; echo >> all.html
cat kibana.3.0/services.html >> all.html; echo >> all.html
cat kibana.3.0/pulldown.html >> all.html; echo >> all.html
cat kibana.3.0/nav.html >> all.html; echo >> all.html
cat kibana.3.0/loader.html >> all.html; echo >> all.html
cat kibana.3.0/rows-array.html >> all.html; echo >> all.html
cat kibana.3.0/index-settings.html >> all.html; echo >> all.html
cat kibana.3.0/the-rest.html >> all.html; echo >> all.html
cat kibana.3.0/importing-schemas.html >> all.html; echo >> all.html
cat kibana.3.0/templated-and-scripted-dashboards.html >> all.html; echo >> all.html
cat kibana.3.0/the-dashboard-directory.html >> all.html; echo >> all.html
cat kibana.3.0/templated-dashboards-.json.html >> all.html; echo >> all.html
cat kibana.3.0/scripted-dashboards-.js.html >> all.html; echo >> all.html
cat kibana.3.0/_parameters.html >> all.html; echo >> all.html
cat kibana.3.0/panels.html >> all.html; echo >> all.html
cat kibana.3.0/_bettermap.html >> all.html; echo >> all.html
cat kibana.3.0/_parameters_2.html >> all.html; echo >> all.html
cat kibana.3.0/_column.html >> all.html; echo >> all.html
cat kibana.3.0/_parameters_3.html >> all.html; echo >> all.html
cat kibana.3.0/_goal.html >> all.html; echo >> all.html
cat kibana.3.0/_parameters_4.html >> all.html; echo >> all.html
cat kibana.3.0/_histogram.html >> all.html; echo >> all.html
cat kibana.3.0/_parameters_5.html >> all.html; echo >> all.html
cat kibana.3.0/_hits.html >> all.html; echo >> all.html
cat kibana.3.0/_parameters_6.html >> all.html; echo >> all.html
cat kibana.3.0/_map.html >> all.html; echo >> all.html
cat kibana.3.0/_parameters_7.html >> all.html; echo >> all.html
cat kibana.3.0/_sparklines.html >> all.html; echo >> all.html
cat kibana.3.0/_parameters_8.html >> all.html; echo >> all.html
cat kibana.3.0/_table.html >> all.html; echo >> all.html
cat kibana.3.0/_parameters_9.html >> all.html; echo >> all.html
cat kibana.3.0/_terms.html >> all.html; echo >> all.html
cat kibana.3.0/_parameters_10.html >> all.html; echo >> all.html
cat kibana.3.0/_text.html >> all.html; echo >> all.html
cat kibana.3.0/_parameters_11.html >> all.html; echo >> all.html
cat kibana.3.0/_trends.html >> all.html; echo >> all.html
cat kibana.3.0/_parameters_12.html >> all.html; echo >> all.html
