. ~/lib.utility2.sh
printf "" > images.html
printf "images/cardinality_error.png\n" >> images.html
shImageToDataUri images/cardinality_error.png >> images.html
printf "images/Exponential.png\n" >> images.html
shImageToDataUri images/Exponential.png >> images.html
printf "images/Gaussian.png\n" >> images.html
shImageToDataUri images/Gaussian.png >> images.html
printf "images/icons/callouts/1.png\n" >> images.html
shImageToDataUri images/icons/callouts/1.png >> images.html
printf "images/icons/callouts/10.png\n" >> images.html
shImageToDataUri images/icons/callouts/10.png >> images.html
printf "images/icons/callouts/2.png\n" >> images.html
shImageToDataUri images/icons/callouts/2.png >> images.html
printf "images/icons/callouts/3.png\n" >> images.html
shImageToDataUri images/icons/callouts/3.png >> images.html
printf "images/icons/callouts/4.png\n" >> images.html
shImageToDataUri images/icons/callouts/4.png >> images.html
printf "images/icons/callouts/5.png\n" >> images.html
shImageToDataUri images/icons/callouts/5.png >> images.html
printf "images/icons/callouts/6.png\n" >> images.html
shImageToDataUri images/icons/callouts/6.png >> images.html
printf "images/icons/callouts/7.png\n" >> images.html
shImageToDataUri images/icons/callouts/7.png >> images.html
printf "images/icons/callouts/8.png\n" >> images.html
shImageToDataUri images/icons/callouts/8.png >> images.html
printf "images/icons/callouts/9.png\n" >> images.html
shImageToDataUri images/icons/callouts/9.png >> images.html
printf "images/icons/caution.png\n" >> images.html
shImageToDataUri images/icons/caution.png >> images.html
printf "images/icons/important.png\n" >> images.html
shImageToDataUri images/icons/important.png >> images.html
printf "images/icons/note.png\n" >> images.html
shImageToDataUri images/icons/note.png >> images.html
printf "images/icons/tip.png\n" >> images.html
shImageToDataUri images/icons/tip.png >> images.html
printf "images/icons/warning.png\n" >> images.html
shImageToDataUri images/icons/warning.png >> images.html
printf "images/lambda.png\n" >> images.html
shImageToDataUri images/lambda.png >> images.html
printf "images/lambda_calc.png\n" >> images.html
shImageToDataUri images/lambda_calc.png >> images.html
printf "images/Linear.png\n" >> images.html
shImageToDataUri images/Linear.png >> images.html
printf "images/percentiles_error.png\n" >> images.html
shImageToDataUri images/percentiles_error.png >> images.html
printf "images/s_calc.png\n" >> images.html
shImageToDataUri images/s_calc.png >> images.html
printf "images/service-manager-win.png\n" >> images.html
shImageToDataUri images/service-manager-win.png >> images.html
printf "images/sigma.png\n" >> images.html
shImageToDataUri images/sigma.png >> images.html
printf "images/sigma_calc.png\n" >> images.html
shImageToDataUri images/sigma_calc.png >> images.html
